### ISSUE TITLE
Error: Cannot find module 'common-css' from 'src'

### ISSUE THREAD

**Issue by apreg** [aaronj1335/webpack-postcss-tools#1]
Hi,

I tried to run the example by issuing webpack command then I got this:

```
c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\node_modules\resolve\lib\sync.js:33
    throw new Error("Cannot find module '" + x + "' from '" + y + "'");
          ^
Error: Cannot find module 'common-css' from 'src'
    at Function.module.exports (c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\node_modules\resolve\lib\sync.js:33:11)
    at resolveImport (c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\index.js:42:20)
    at c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\index.js:68:15
    at c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\node_modules\postcss\lib\container.js:226:34
    at c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\node_modules\postcss\lib\container.js:132:26
    at Root.each (c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\node_modules\postcss\lib\container.js:107:22)
    at Root.eachInside (c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\node_modules\postcss\lib\container.js:131:21)
    at Root.eachAtRule (c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\node_modules\postcss\lib\container.js:224:25)
    at process (c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\index.js:62:16)
    at Object.makeVarMap (c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules\webpack-postcss-tools\index.js:106:3)
```

**Comment by aaronj1335** [comment]
what webpack command did you issue?

**Comment by apreg** [comment]
I wrote simply webpack into the console

**Comment by aaronj1335** [comment]
try running `npm run build`. also what directory did you run that command from?

**Comment by apreg** [comment]
c:\WORKSPACE\JS\webpack-postcss-tools\example\

**Comment by aaronj1335** [comment]
does `npm run build` work?

**Comment by apreg** [comment]
No, it does not but I'm on Windows if that matters. You've probably already guessed that out from the log...

**Comment by apreg** [comment]
0 info it worked if it ends with ok
1 verbose cli [ 'C:\DEVELOPMENT\nodejs\\node.exe',
1 verbose cli   'C:\DEVELOPMENT\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.5.1
3 info using node@v0.12.0
4 verbose node symlink C:\DEVELOPMENT\nodejs\node.exe
5 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
6 info prebuild example-app@0.0.0
7 info build example-app@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info example-app@0.0.0 Failed to exec build script
10 verbose stack Error: example-app@0.0.0 build: `./bin/build.js`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\DEVELOPMENT\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (C:\DEVELOPMENT\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1008:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
11 verbose pkgid example-app@0.0.0
12 verbose cwd c:\WORKSPACE\JS\webpack-postcss-tools\example
13 error Windows_NT 6.3.9600
14 error argv "C:\DEVELOPMENT\nodejs\\node.exe" "C:\DEVELOPMENT\nodejs\node_modules\npm\bin\npm-cli.js" "run" "build"
15 error node v0.12.0
16 error npm  v2.5.1
17 error code ELIFECYCLE
18 error example-app@0.0.0 build: `./bin/build.js`
18 error Exit status 1
19 error Failed at the example-app@0.0.0 build script './bin/build.js'.
19 error This is most likely a problem with the example-app package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     ./bin/build.js
19 error You can get their info via:
19 error     npm owner ls example-app
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by aaronj1335** [comment]
i'm not on windows, and this is [working on linux](https://travis-ci.org/aaronj1335/webpack-postcss-tools) and my laptop, so i can't debug it.

`npm run build` may be failing because the commands are of the form `./bin/build.js` instead of `node bin/build.js`, but i'm not familiar enough with windows to know how node works there. i would definitely appreciate any help you could lend here since you're on windows!

**Comment by apreg** [comment]
I'd really like to help you but first I have to find out how to debug. I've heard about node-inspector and such but could not make it work.

**Comment by aaronj1335** [comment]
i use `npm install -g node-inspector` and then `node-debug ./node_modules/.bin/webpack --bail`.

**Comment by apreg** [comment]
Great thx, I'll try that out after I finished experimenting with webstorm's debugger. Actually it seems pretty useful.

**Comment by apreg** [comment]
So this is what I found: I think in node-modules-paths.js line 9 this regexp does not work correctly:

```
 if (/^([A-Za-z]:)/.test(start)) {
```

when the value of start is e.g. src because of this definition in webpack.config.js

```
var map = webpackPostcssTools.makeVarMap('src/index.css');
```

then the prefix remains on default '/' which yields these kinda paths:
"/c:\WORKSPACE\JS\webpack-postcss-tools\example\node_modules"
So, I simply changed that regexp to /^([A-Za-z]*) and a valid webpack bundle was my reward:).

**Comment by apreg** [comment]
And maybe in bin\build.js line 17 there is a missing '\'. There should be 4 backslashes and not 3 but correct me if I'm wrong.

```
  new RegExp(buildFilenameEscaped.replace('\\\\.[hash]', ''));
```

**Comment by aaronj1335** [comment]
right on -- so is this something we can fix entirely in this repo? or is it an issue with the `resolve` package?

**Comment by apreg** [comment]
I'm afraid it is an issue with resolve so we cannot fix it here.

**Comment by apreg** [comment]
What should that `:` do btw?
I only found this:
https://regex101.com/r/oY7xE8/1

**Comment by aaronj1335** [comment]
can we fix it here if we make relative paths absolute?

> What should that `:` do btw?

the one in `node-modules-paths.js:9`? i believe it's looking for absolute paths in windows (i.e. the drive name in `C:\...`).

**Comment by apreg** [comment]
Ah, I see. Yes, with absolute paths it should work I guess.

**Comment by apreg** [comment]
I tried in `node_modules/webpack-postcss-tools/index.js : 70` 

```
process(resolveImport(stripped, path_.resolve(filename)));
```

but other problems came up that needs more debug but I'm going bed now.

**Comment by aaronj1335** [comment]
hah right on. if you're feeling motivated, i'm sure [resolve](https://www.npmjs.com/package/resolve) would appreciate any bug fixes as well :smile:

**Comment by apreg** [comment]
I still think with absolute paths we can solve it here in this codebase.

**Comment by aaronj1335** [comment]
right on, let me know if you're able to get it working.

**Comment by apreg** [comment]
It looks like with absolute paths `makeVarMap` creates the map correctly but I got exception after that.

```
'.' is not recognized as an internal or external command,
operable program or batch file.
c:\WORKSPACE\JS\webpack-postcss-tools\example\bin\build.js:27
    throw new Error('webpack build failed');
          ^
Error: webpack build failed
    at build (c:\WORKSPACE\JS\webpack-postcss-tools\example\bin\build.js:27:11)
    at Object.<anonymous> (c:\WORKSPACE\JS\webpack-postcss-tools\example\bin\build.js:35:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.runMain [as _onTimeout] (module.js:501:10)
    at Timer.listOnTimeout (timers.js:110:15)

Process finished with exit code 1
```

**Comment by aaronj1335** [comment]
hey, so i made the unit tests a bit more platform-independent in 3a88eec. let me know if that helps!

**Comment by apreg** [comment]
What do you think about my changes? 
5fdf2c38f1b116991e531f9894179bbce3202fc3
0b8ee4ba03cc880e7ab941132f7163bc57dceeda

**Comment by apreg** [comment]
When I issue `npm run dev` then I can see index.html with full of trash truck gifs and `npm run build` generates an index.html in dist folder with a clean console.

**Comment by aaronj1335** [comment]
looks awesome! i think you should submit a PR!

i will want to keep the indentation at 2 spaces tho, so 5fdf2c3 will need to change a bit. but we can discuss all that in the PR issue.

**Comment by apreg** [comment]
cool

**Comment by apreg** [comment]
Have you checked my PR? It's the first for me so I hope I did not screw it up :)

**Comment by aaronj1335** [comment]
hah no man i think you're doing great -- ci tests pass so that's good! i'm at work now, so i was just going to take a closer look tonight or tomorrow. hopefully it's not blocking you on anything.

**Comment by apreg** [comment]
Nah, it's not blocking me. Great, thx.
