### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by jantimon** [aaronj1335/webpack-postcss-tools#9]
Hi,
might be my fault but I really don't get what this package does by reading the readme.
All it does is:

> these tools give you the full power of webpack's dependency management without sacrificing must-have css features.
> Which must have css features do you mean?

What does `var map = webpackPostcssTools.makeVarMap('src/index.css');` do?

Why do you use `postcss-custom-properties`, `postcss-custom-media` and `postcss-custom-selector`?

What does `webpackPostcssTools.prependTildesToImports` do?

Maybe you could add some source code comments or a feature list.

**Comment by aaronj1335** [comment]
> Maybe you could add some source code comments

Like [this](https://github.com/aaronj1335/webpack-postcss-tools/blob/a04dc1e8d321a24d754d24f31a4d14d543d1c4c4/index.js#L120) or [this](https://github.com/aaronj1335/webpack-postcss-tools/blob/a04dc1e8d321a24d754d24f31a4d14d543d1c4c4/index.js#L14)?

> Why do you use postcss-custom-properties, postcss-custom-media and postcss-custom-selector?

Those are PostCSS plugins that allow you to use CSS features that aren't available in all of the browsers your CSS will be used in. These are there as an example, though the specific plugins you use depend on what features your CSS uses. For example, if you wanted to author CSS with variables and transpile those to concrete values before sending them to the browser, you could use the postcss-custom-properties plugin. The decision of which plugins to use depends on your CSS and what browsers your users have.

> Which must have css features do you mean?

Yea this could be worded better. The specific feature is CSS variables, which are difficult to integrate with Webpack modules. Consider a `button.css` file that styles buttons using variables defined in a `theme.css` file. If these are treated as Webpack modules and the PostCSS loader is used, it runs on the individual files before Webpack combines them, so PostCSS can't resolve variables defined in `theme.css` and referenced in `button.css`.

Maybe a better wording would be this?

> these tools give your css the benefits of webpack's dependency management but still allow postcss to run in the context of all the css.

This library has relatively low-level utilities. If you're new to treating individual CSS files as modules, I'd recommend the [`css-modules`](https://github.com/css-modules/webpack-demo) approach.

**Comment by jantimon** [comment]
Wow thanks for the explanation - so all it does is enabling css-wide postcss variables?

**Comment by aaronj1335** [comment]
Heh, it's more complicated than that... on it's own, `makeVarMap` can make an object mapping CSS variable names to values in a manner similar to how a browser might do it. You'd still need PostCSS to transpile the variables. 

Honestly the whole CSS dependency management thing was kind of a mess when I wrote this, and it hasn't gotten that much better since. These utilities are just a band-aid that fit my use-case, but `css-modules` is a much more thought-out approach (though it can introduce a bit of overhead). I feel like there's a lot of disagreement over the best approach, and a lot of smart, solid folks would even say this is over-engineering.

**Comment by jantimon** [comment]
I am quite happy with css-modules so far.
It allows you to use clean class names without worries like here:

https://github.com/jantimon/clean-commit-gui/blob/master/app/components/diffList/diffListEntry/diffListEntry.scss
